### PR TITLE
Use get for adapter.namespace

### LINKED ISSUE #70: TypeError: adapter.namespace.split is not a function with ember-django-adapter
Using ember-django-adapter, `namespace` is a computed property making `adapter.namespace.split('/') fail.

### PR DESCRIPTION
**Pull request by nanuxbe**
Fix #70 

- Add adapter for the dog model with namespace as a computed property (which makes original tests fail).
- Fixeissue by using `adapter.get('namespace')` instead of `adapter.namespace` in `store/admin.js`

### CODE REVIEW

File: addon/stores/admin.js [hunk 1]
```diff
@@ -20,8 +20,8 @@ export default Store.extend({
       const adapter = this._super(type);
       const adminService = getOwner(this).lookup('service:admin');
 
-      if (adapter.namespace) {
-        namespaces = adapter.namespace.split('/');
+      if (adapter.get('namespace')) {
```
Comment (bcardarella) [inline addon/stores/admin.js]: Can you please change this to:

```js
get(adapter, 'namespace')
```

File: addon/stores/admin.js [hunk 2]
```diff
@@ -20,8 +20,8 @@ export default Store.extend({
...
+        namespaces = adapter.get('namespace').split('/');
```
Comment (bcardarella) [inline addon/stores/admin.js]: same as above

**Comment by martndemus** [comment]
@nanuxbe Excuse us for the slow reaction!
@bcardarella Can you publish a new patch version?
